- name: deploy lovely-golden
  hosts: servers
  gather_facts: no
  tasks:
      - name: Update Git branch
        ansible.builtin.git:
            repo: git@github.com:nstuder/lovely-golden-cms.git
            dest: /home/nstuder/lovely-golden
            version: main
            update: yes

      - name: Create and start services
        community.docker.docker_compose:
            project_src: /home/nstuder/lovely-golden
            build: true
        register: output
